# BL40A2010 Introduction to IoT-Based Systems

## Assignment 3, DD.MM.YYYY

### Author: 

**(1) Compute the following for a ring topology of $N\geq3$ nodes considering that the network in unweighted and the links are directed. The result will give these number as a function of $N$.** 

Answer:

(a) Degree of nodes: 2, in a ring each node is connected one to two other nodes and never the same. 
	
(b) Adjacent matrix: Example adjacent ring matrix. The order of nodes can vary.
$$
A = \begin{pmatrix} 
 0 & 1 & 1 & 0 & 0 &... & 0 \\
 1 & 0 & 0 & 1 & 0 &... & 0 \\
 1 & 0 & 0 & 0 & 1 &... & 0 \\
 0 & 1 & 0 & 0 & 1 &... & 0 \\
 ... & ... & ... & ... & ... & ... & ... \\ 
 0 & 0 & 0 & 0 & 0 &... & 0
\end{pmatrix}
$$

(c) Diameter: $N/2$ Network keeps getting biger 

(d) Clustering coefficient of the nodes: $0$ In a ring the nodes are connected only to neighbours and there is no connection between the neighbours.



**(2) Use NetworkX to draw and analyze a ring topology with 5 nodes. Verify if the results previously obtained are valid.**

In [51]:
!pip install -r requirements.txt
!pip install --upgrade networkx
!pip install --upgrade scipy

import networkx as nx 
import matplotlib.pyplot as plt 
import scipy as sp
import numpy as np

Requirement already up-to-date: networkx in /srv/conda/envs/notebook/lib/python3.7/site-packages (2.5)
Requirement already up-to-date: scipy in /srv/conda/envs/notebook/lib/python3.7/site-packages (1.5.2)


In [52]:
T = nx.Graph()
T = nx.complete_graph(5)
T.remove_edge(0, 1)
T.remove_edge(0, 3)
T.remove_edge(1, 2)
T.remove_edge(2, 4)
T.remove_edge(3, 4)

nx.draw_networkx(T, node_color='red', font_color='black', edge_color='blue', font_weight='bold',  node_size=700)
plt.axis('off')
plt.show()

In [53]:
G.degree()

DegreeView({0: 2, 1: 2, 2: 2, 3: 2, 4: 2})

a) Node degree is $2$

In [54]:
A=nx.adjacency_matrix(G)
print(A.todense())

[[0 0 1 0 1]
 [0 0 0 1 1]
 [1 0 0 1 0]
 [0 1 1 0 0]
 [1 1 0 0 0]]


b) The adjacent matrix does not match example, mostly because order of the nodes connected is different. 

In [55]:
nx.diameter(G)

2

c) Diameter: $2$

In [56]:
nx.clustering(G)

{0: 0, 1: 0, 2: 0, 3: 0, 4: 0}

d) Clustering coefficient: $1$

**(3) Analyze the ring topology with size 20 ($N=20$) as a communication network (i.e. how data travel to a point to another in the network) based on the node degree, the network diamenter and the cluster coefficient.**

Answer:

**(4) Consider the ring network from the previous question. The network performance depends on its diameter. As a designer, you can add one new node in the network (and an unlimited number of links that this node is part) . Justify your decision and evaluate how much better the network is. Generalize this finding as a function of $N$.**

*Hint:*  Follow Exercise 1 approach to generalize the finding.

Answer: